# group ids or account ids can be retrieved with @username_to_id_bot
BOT_TOKEN="5144233701:AAGuO-qtl3UsG6sJ2AWRrTZSdncfhMnnhCg"
BOT_OWNER=420038215



WAITING_FOR_FILE=False
IS_DATA_INSERTED=False
CAN_INSERT_NAMES=False
IS_DATA_PROCESSED=False
IS_SOMETHING_PROCESSED=False
CAN_ENTER_NUMBER=True